name: Lighthouse Performance Check
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Serve Built Site
        run: |
          npx serve -s dist -l 5173 &
          sleep 10  # Increased wait time

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:5173
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
        continue-on-error: true

  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Serve Built Site
        run: |
          npx serve -s dist -l 5173 &
          sleep 10  # Increased wait time

      - name: Run Accessibility Scan
        uses: pa11y/action@main
        with:
          url: http://localhost:5173
          standard: WCAG2AAA
        continue-on-error: true
