name: Lighthouse Performance Check
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Project
        run: npm run build
      
      - name: Serve Built Site
        run: |
          npx serve -s dist &
          sleep 5
      
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:5000
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Accessibility Scan
        uses: dequelabs/axe-core-action@v1
        with:
          run-only-on-changed-files: true